### ISSUE TITLE
Naver OAuth2 Convert Token Error

### ISSUE THREAD

**Issue by JaeYeonLee0621** [RealmTeam/django-rest-framework-social-oauth2#196]
I tried to use **naver oauth2** but got some issues.

I set only **id** and **email** are necessary and others are optional in naver administration setting page.

So i only got id and email in response. But `def _dom_value` try to find the other value like username, nickname etc, so **list index out of range** error coming up.

Can you check about this.
Thanks.

## Error Log
```
Internal Server Error: /auth/convert-token
Traceback (most recent call last):
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/braces/views/_forms.py", line 24, in dispatch
    return super(CsrfExemptMixin, self).dispatch(*args, **kwargs)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/rest_framework_social_oauth2/views.py", line 70, in post
    url, headers, body, status = self.create_token_response(request._request)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/oauth2_provider/views/mixins.py", line 123, in create_token_response
    return core.create_token_response(request)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/oauth2_provider/oauth2_backends.py", line 138, in create_token_response
    headers, extra_credentials)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 87, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/rest_framework_social_oauth2/oauth2_endpoints.py", line 60, in create_token_response
    request, self.default_token_type)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/grant_types/refresh_token.py", line 60, in create_token_response
    self.validate_token_request(request)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/rest_framework_social_oauth2/oauth2_grants.py", line 94, in validate_token_request
    user = backend.do_auth(access_token=request.token)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/social_core/utils.py", line 259, in wrapper
    return func(*args, **kwargs)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/social_core/backends/oauth.py", line 410, in do_auth
    data = self.user_data(access_token, *args, **kwargs)
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/social_core/backends/naver.py", line 44, in user_data
    'username': self._dom_value(dom, 'name'),
  File "/Users/jaeyeonlee/Documents/MoveDot/venv/lib/python3.7/site-packages/social_core/backends/naver.py", line 62, in _dom_value
    return dom.getElementsByTagName(key)[0].childNodes[0].data
IndexError: list index out of range
```

**Comment by PhilipGarnero** [comment]
Just checked out the code and this was due to an old version of the naver backend code relying on html elements so of course it could not work when we do everything via API.
Updating should do the trick.
